import type { GenerateVariantsInput } from "./types.ts";

export function buildPrompt(input: GenerateVariantsInput): string {
  return [
    "You generate UI code variant proposals for a local development tool.",
    "Return JSON only. Do not include markdown, code fences, explanations, or surrounding prose.",
    "",
    "Output schema:",
    "[",
    "  {",
    '    "title": "Variant A",',
    '    "description": "Short explanation of the visible UI change",',
    '    "changes": [',
    "      {",
    `        "file": ${JSON.stringify(input.selectedSource.file)},`,
    '        "edits": [',
    "          {",
    '            "search": "exact original text from the provided code range",',
    '            "replace": "replacement text"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "]",
    "",
    "Rules:",
    `- Return exactly ${input.count} variants if possible.`,
    `- Every change must target only this file: ${input.selectedSource.file}.`,
    "- Use search/replace edits only. Do not output diffs.",
    "- The search text must be copied exactly from the provided code range.",
    "- Each search text must appear uniquely in the provided code range.",
    "- Keep changes small and safe for Fast Refresh.",
    "- Only change text, labels, props, className, or size-like values.",
    "- Do not add imports.",
    "- Do not change hooks, component structure, function signatures, data flow, or other files.",
    "- Do not invent design system APIs.",
    "- If a safe variant cannot be produced, return fewer variants.",
    "",
    "Selected source:",
    JSON.stringify(input.selectedSource, null, 2),
    "",
    "User instruction:",
    input.instruction,
    "",
    "Code range:",
    JSON.stringify(
      {
        file: input.codeRange.file,
        startLine: input.codeRange.startLine,
        endLine: input.codeRange.endLine,
        content: input.codeRange.content,
      },
      null,
      2,
    ),
  ].join("\n");
}
